rbac.yamlapiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-app-readonly
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods","configmaps"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-app-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: secure-app
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secure-app-readonly
